include(
    ":app",
    ":base-extensions-test",
    ":core-register",
    ":feature-editor",
    ":feature-notes",
    ":platform-loadable",
    ":platform-register",
    ":platform-register-test"
)
include(":platform-extensions")
include(":feature-notes-test")
