include(
    ":app",
    ":base-extensions-test",
    ":core-register",
    ":feature-editor",
    ":feature-notes",
    ":platform-extensions",
    ":platform-register",
    ":platform-register-test"
)
